# Generated by Django 3.1.7 on 2021-06-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210607_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
